# Generated by Django 3.1.4 on 2020-12-17 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('due_date', models.CharField(default='', max_length=1000)),
                ('start_date', models.CharField(blank=True, default='', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
